vr_teleop_action_server:
  ros__parameters:
    sim_path: ./mujoco-3.5.0/bin/simulate
    model_path: ./assets/mjcf/garmi_teleop.xml
    meta_data:
      transport: zmq
      host: "tcp://127.0.0.1"
      server_port: "7000"
      client_port: "2000"
      world_name: world
      simulation_name: vr_teleop
    filter:
      time_constant: 0.02
      damping: 1.0
    initializers:
      markers_initializer:
        topic: /tf
        frame_id: base_link
        frames:
          hand_left_ref: arm_0_fr3_link7
          hand_right_ref: arm_1_fr3_link7
          head_ref: head
      joint_state_initializer:
        topic: /joint_states
        joints:
          teleop_lift_0_lower_joint: lift_0_lower_joint
          teleop_lift_0_upper_joint: lift_0_upper_joint
          teleop_arm_0_fr3_joint1: arm_0_fr3_joint1
          teleop_arm_0_fr3_joint2: arm_0_fr3_joint2
          teleop_arm_0_fr3_joint3: arm_0_fr3_joint3
          teleop_arm_0_fr3_joint4: arm_0_fr3_joint4
          teleop_arm_0_fr3_joint5: arm_0_fr3_joint5
          teleop_arm_0_fr3_joint6: arm_0_fr3_joint6
          teleop_arm_0_fr3_joint7: arm_0_fr3_joint7
          teleop_arm_0_gripper_fr3_finger_joint1: arm_0_gripper_fr3_finger_joint1
          teleop_arm_0_gripper_fr3_finger_joint2: arm_0_gripper_fr3_finger_joint2
          teleop_head_pan_joint: head_pan_joint
          teleop_head_tilt_joint: head_tilt_joint
          teleop_arm_1_fr3_joint1: arm_1_fr3_joint1
          teleop_arm_1_fr3_joint2: arm_1_fr3_joint2
          teleop_arm_1_fr3_joint3: arm_1_fr3_joint3
          teleop_arm_1_fr3_joint4: arm_1_fr3_joint4
          teleop_arm_1_fr3_joint5: arm_1_fr3_joint5
          teleop_arm_1_fr3_joint6: arm_1_fr3_joint6
          teleop_arm_1_fr3_joint7: arm_1_fr3_joint7
          teleop_arm_1_gripper_fr3_finger_joint1: arm_1_gripper_fr3_finger_joint1
          teleop_arm_1_gripper_fr3_finger_joint2: arm_1_gripper_fr3_finger_joint2

    publishers:
      left_arm_publisher:
        topic: /garmi_arm_0_controller/joint_trajectory
        rate: 100
        joints:
          arm_0_fr3_joint1:
            from: teleop_arm_0_fr3_joint1
            type: joint_angular_position
          arm_0_fr3_joint2:
            from: teleop_arm_0_fr3_joint2
            type: joint_angular_position
          arm_0_fr3_joint3:
            from: teleop_arm_0_fr3_joint3
            type: joint_angular_position
          arm_0_fr3_joint4:
            from: teleop_arm_0_fr3_joint4
            type: joint_angular_position
          arm_0_fr3_joint5:
            from: teleop_arm_0_fr3_joint5
            type: joint_angular_position
          arm_0_fr3_joint6:
            from: teleop_arm_0_fr3_joint6
            type: joint_angular_position
          arm_0_fr3_joint7:
            from: teleop_arm_0_fr3_joint7
            type: joint_angular_position
      right_arm_publisher:
        topic: /garmi_arm_1_controller/joint_trajectory
        rate: 100
        joints:
          arm_1_fr3_joint1:
            from: teleop_arm_1_fr3_joint1
            type: joint_angular_position
          arm_1_fr3_joint2:
            from: teleop_arm_1_fr3_joint2
            type: joint_angular_position
          arm_1_fr3_joint3:
            from: teleop_arm_1_fr3_joint3
            type: joint_angular_position
          arm_1_fr3_joint4:
            from: teleop_arm_1_fr3_joint4
            type: joint_angular_position
          arm_1_fr3_joint5:
            from: teleop_arm_1_fr3_joint5
            type: joint_angular_position
          arm_1_fr3_joint6:
            from: teleop_arm_1_fr3_joint6
            type: joint_angular_position
          arm_1_fr3_joint7:
            from: teleop_arm_1_fr3_joint7
            type: joint_angular_position
      head_publisher:
        topic: /garmi_head_controller/joint_trajectory
        rate: 100
        joints:
          head_pan_joint:
            from: teleop_head_pan_joint
            type: joint_angular_position
          head_tilt_joint:
            from: teleop_head_tilt_joint
            type: joint_angular_position
      torso_publisher:
        topic: /garmi_lift_controller/joint_trajectory
        rate: 100
        joints:
          lift_0_lower_joint:
            from: teleop_lift_0_lower_joint
            type: joint_linear_position
